excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - UpSkill/ApplicationDelegates/*.swift
  - UpSkill/*/*.storyboard
  - UpSkillTests/*.swift
  - UpSkillUITests/*.swift

disabled_rules:
  - trailing_whitespace

# customised rules
line_length:
  warning: 180
  error: 200

